### ISSUE TITLE
感谢您的付出

### ISSUE THREAD

**Issue by huaxuanHan** [lcyluo/EasyPhotos#1]
我最近在使用这个https://github.com/joker-fu/EasyPhotos，但是遇到了Android7/8/9上面不能使用的问题，看你这个给解决了，挺好的，不过你这个还需要自己编译，要是能直接引用就更好了

**Comment by huaxuanHan** [comment]
试了一下，挺好的，就是有两个小问题，一是图片加水印时候，图片过大会报错java.lang.RuntimeException: Canvas: trying to draw too large(192000000bytes) bitmap.二是拼图完成之后可能出现图片无法显示的问题，有图片信息但是图片显示不出来

**Comment by lcyluo** [comment]
拼图功能出现问题，有极大可能是Android10之后，存储发生改变导致，因为我平时项目中没有用到拼图，所以那块就没去处理，也没去测试，只是保证图片选择和拍摄能正常使用；


引用方法我已经修改在ReadMe中了，你可以参考一下！

**Comment by huaxuanHan** [comment]
拼图功能我也不用，就是测试时候发现了这个问题，看能修复就修复一下，另外我在使用的时候发现了另一个问题，你这个项目必须在主项目的manifest里面添加<provider
            android:name="androidx.core.content.FileProvider"
            android:authorities="com.huantansheng.easyphotos.demo.fileprovider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/file_paths_public" />
        </provider>这个provider吗？如果项目本身有一个provider的话，两个有冲突，不能同时使用，这个问题我没详细的测试，我这边项目有点紧，等我有空的话再试一下看是不是我使用的问题

**Comment by huaxuanHan** [comment]
好的，感谢
