### ISSUE TITLE
提个建议，也算需求吧

### ISSUE THREAD

**Issue by huaxuanHan** [lcyluo/EasyPhotos#2]
打开相机的时候能不能加一个条件打开前置或者后置相机，因为有一些专用设备，设备就固定放在那，程序装好就不再动，打开相机时候默认打开前置或后置相机，就不用工作人员再多点击一次了，您看这个改动方不方便做？再次感谢您的辛苦付出

**Comment by lcyluo** [comment]
其实是支持设置调用的摄像头的，在创建AlbumBuilder时支持传入cameraFacing；
    /**
     * 设置前置摄像头或者后置摄像头
     *
     * @param facing 摄像头ID
     * @return @return AlbumBuilder
     */
    public AlbumBuilder setCameraFacing(int facing) {
        Setting.cameraFacing = facing;
        return AlbumBuilder.this;
    }

facing是需要默认调起的摄像头ID，因为我测试到不同设备的前置或者后置摄像头的ID不同，所以这块API就考虑到根据不同的设备去获取需要的摄像头ID，然后调起，你可以试试看能否满足你的需求。

目前大部分手机是会默认打开相机上一次选择的前后置设置，可能部分三方设备没有保存这个设置，就会导致可能每次都需要点击切换才行。

**Comment by lcyluo** [comment]
有部分定制设备，它的后置摄像头其实是放在前置位置的，所以很奇葩，有那种前后置反着的，所以我这边api就没有直接提供设置Front还是Back，而是让开发自己传需要的摄像头ID。方便适配。

**Comment by lcyluo** [comment]
我先关闭了。
