### ISSUE TITLE
奔溃

### ISSUE THREAD

**Issue by NingXiaAndroidYP** [lcyluo/EasyPhotos#7]
![1733907372784](https://github.com/user-attachments/assets/956d364b-96a7-4152-afb0-40459ae9fe59)

**Comment by lcyluo** [comment]
在 你项目中添加 Android 14 前台服务适配即可
<uses-permission android:name="android.permission.FOREGROUND_SERVICE_CAMERA" />

**Comment by lcyluo** [comment]
`<uses-permission android:name="android.permission.FOREGROUND_SERVICE_CAMERA" />`

**Comment by lcyluo** [comment]
或者引用最新的版本，也可以解决这个问题；
